[tool.poetry]
name = "sync-downloaded-files"
version = "0.1.0"
description = ""
authors = ["John L. Villalovos"]

[tool.poetry.dependencies]
python = "^3.8"
attrs =  "^19.3.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.1"
mypy = "^0.782"
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
